# Generated by Django 5.1.7 on 2025-06-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('cost', models.IntegerField()),
                ('products', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=100)),
                ('numberOfStores', models.IntegerField()),
                ('code', models.CharField(max_length=20,unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20,unique=True)),
                ('password', models.CharField(max_length=20)),
                ('logedIn', models.BooleanField()),
                ('start', models.DateTimeField()),
                ('register_id', models.CharField(max_length=20)),
                ('store_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeWorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('numberInstances', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('items', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('image', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('limitedEdition', models.BooleanField()),
                ('description', models.TextField()),
                ('maxItems', models.IntegerField()),
                ('minItems', models.IntegerField()),
                ('numItems', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField()),
                ('store_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20,unique=True)),
                ('password', models.CharField(max_length=20)),
                ('numberEmployees', models.IntegerField()),
                ('numberOfCashRegisters', models.IntegerField()),
                ('company_id', models.IntegerField()),
            ],
        ),
    ]
