# Generated by Django 5.1.7 on 2025-07-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_register_employee_id_alter_employee_register_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='incart',
            name='code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='incart',
            name='register_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='incart',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
