# Generated by Django 5.1.7 on 2025-07-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_incart_code_incart_register_id_alter_incart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='incart',
            name='toBuy',
            field=models.IntegerField(default=0),
        ),
    ]
