# Generated by Django 5.1.7 on 2025-07-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_incart_tobuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworktime',
            name='store_id',
            field=models.IntegerField(default=5),
        ),
    ]
