# Generated by Django 5.1.7 on 2025-07-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_employeeworktime_store_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('cost', models.IntegerField()),
                ('products', models.JSONField()),
                ('timeRefund', models.DateTimeField()),
            ],
        ),
    ]
