# Generated by Django 5.1.7 on 2025-08-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_refundbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='newPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
