# Generated by Django 5.1.7 on 2025-08-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_product_newprice_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='cashier', max_length=20),
        ),
    ]
